version: '3.6'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      STARTUP_UPDATE_VENDORS: 'true'
      YII_ENV: 'dev'
      YII_DEBUG: 'true'
      DATABASE_DSN: 'pgsql:host=db;port=5432;dbname=postgres;user=postgres;password=1'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  db: {}
