#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', getenv('YII_DEBUG') === 'true');
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV') ?? 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/console/config/app.php'
);

try {
    $application = new yii\console\Application($config);
    $exitCode = $application->run();
    exit($exitCode);
} catch (\yii\base\InvalidConfigException $exception) {
    echo "Exception: ", $exception->getMessage(), "\n";
    exit(1);
}
